version: '3.8'
services:
  gh-runner:
    build: ./github_runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # This allows the runner to run docker commands on the host OS
    privileged: true